# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMiLplN7dbHT2wNUAEP5T7YZtehS7r3a
"""

!pip install -U -q "google-generativeai>=0.7.2" # Install the Python SDK

import google.generativeai as genai

from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel('gemini-1.5-flash')
response = model.generate_content("give me python code for basic calculator")
print(response.text)

def basic_calculator_loop():
  """Performs basic arithmetic operations in a loop."""
  while True:
    try:
      num1 = float(input("Enter the first number (or 'q' to quit): "))
      op = input("Enter an operator (+, -, *, /): ")
      num2 = float(input("Enter the second number: "))

      if op == "+":
        result = num1 + num2
      elif op == "-":
        result = num1 - num2
      elif op == "*":
        result = num1 * num2
      elif op == "/":
        if num2 == 0:
          result = "Division by zero!"
        else:
          result = num1 / num2
      else:
        result = "Invalid operator"

      print("Result:", result)

    except ValueError:
      print("Invalid input. Please enter numbers only.")
      continue # Go to the next iteration of the loop
    except KeyboardInterrupt: # handle Ctrl-C
      print("\nCalculator stopped.")
      break # exit the loop

basic_calculator_loop()

!apt-get install git

!git config --global user.email "kentaraken8ge8@gmail.com"
!git config --global user.name "kentaraken"

!git clone https://github.com/kentaraken8ge8/simple-calculator

# Commented out IPython magic to ensure Python compatibility.
# %cd simple-calculator